name: C Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc make

    - name: Build with Make
      run: make

    - name: Run the program with test input
      run: |
        echo -e "Иванов И.И.\n1234567\n2000 1 15\nПетров П.П.\n7654321\n1995 5 20\nСидоров С.С.\n5551234\n1988 10 30\nКозлов К.К.\n3334445\n1985 7 12\nСмирнов С.С.\n7778889\n1998 12 5\nВасильев В.В.\n9990001\n1979 9 18\nИванов" | ./note2_program
